"""initial schema

Revision ID: ee10689cdbe6
Revises: 
Create Date: 2026-05-25 18:50:29.698928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee10689cdbe6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slots', 'is_booked')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slots', sa.Column('is_booked', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
